speech:
  # Включить распознавание голосовых сообщений
  enabled: true
  
  # Язык распознавания
  language: "ru"
  
  # Локальная модель Whisper
  # Доступные размеры: tiny, base, small, medium, large
  # tiny (39MB) - быстро, низкое качество
  # base (74MB) - базовое качество
  # small (244MB) - хорошее качество
  # medium (1.5GB) - отличное качество (рекомендуется)
  # large (2.9GB) - максимальное качество, медленно
  whisper_model: "small"
  
  # Путь к FFmpeg
  # Windows (без Docker): "C:\\ffmpeg\\bin\\ffmpeg.exe"
  # Docker: "" (пусто - FFmpeg уже установлен в контейнере)
  # Linux/Mac: "" (пусто - автопоиск в системе)
  ffmpeg_path: ""

# Базовый URL веб-приложения (для ссылок в ботах)
# ПРИМЕЧАНИЕ: Переопределяется переменной окружения BASE_URL (приоритет выше)
# Автоматически определяется из ngrok API если ngrok запущен
# Fallback: http://localhost:8000
base_url: "http://localhost:8000"

# TTL сессии в секундах (по умолчанию 24 часа)
session_ttl: 86400

# Максимум активных сессий одновременно
max_active_sessions: 100

# Интервал очистки старых сессий (секунды)
cleanup_interval: 360

# Ответы ботов (Telegram и VK)
telegram_responses:
  # Приветственное сообщение при /start
  start_greeting: |
    👋 Привет, {user_name}!
    
    Я бот технической поддержки. Задавайте вопросы о работе с компьютером, программами или корпоративными системами — постараюсь помочь!
    
    💡 Посмотрите наш <a href="{base_url}/faq">FAQ с ответами на популярные вопросы</a>

  # Промпт для формирования ответа из базы знаний
  kb_craft_user_prompt: |
    Вопрос из базы: {question}
    Запись базы (источник): {answer}

    Сформируй дружелюбный, понятный пользователю ответ в 2-5 предложениях, сохраняя суть и давая практические шаги, если нужно.

  # Сообщения при ошибках
  voice_processing_error: "❌ Не удалось получить голосовое сообщение."
  speech_recognition_error: "❌ Не удалось распознать речь. Попробуйте еще раз или напишите текстом."
  voice_download_error: "❌ Не удалось скачать голосовое сообщение."
  voice_general_error: "❌ Произошла ошибка при обработке голосового сообщения. Попробуйте написать текстом."

  # Сообщения для неподдерживаемых типов
  unsupported_message_response:
    - "Я обрабатываю только текст. Напишите вопрос словами, пожалуйста."
    - "Фото, файлы и голосовые пока не читаю — опишите проблему текстом."

  # Сообщение при обработке
  processing_message: "⏳ Обрабатываю ваш запрос..."

vk_responses:
  # Сообщения при ошибках голосовых сообщений
  voice_processing_error: "❌ Не удалось получить голосовое сообщение."
  speech_recognition_error: "❌ Не удалось распознать речь. Попробуйте еще раз или напишите текстом."
  voice_download_error: "❌ Не удалось скачать голосовое сообщение."
  voice_general_error: "❌ Произошла ошибка при обработке голосового сообщения. Попробуйте написать текстом."

  # Сообщения для оператора
  operator_connected: "✅ Оператор будет подключен. Ожидайте ответа."
  operator_cancelled: "Отмена подключения оператора."
  operator_request_confirmation: |
    Хотите связаться с оператором?

    Мы создадим заявку и оповестим операторов, как только вы подтвердите запрос.

    ⏱ Среднее время ответа: {avg_response_time}

    Если хотите подключить оператора — отправьте 'да'.

  # Сообщение при обработке
  processing_message: "⏳ Обрабатываю ваш запрос..."

  # Подтверждение выбора опции
  option_confirmation: "Вы выбрали: {option}"