# Настройки симулированных пользователей
characters:
  easy:
    name: "Новичок Вася"
    emoji: "🙂"
    description: "Только начал работать, задает простые вопросы"
    difficulty: "easy"
  medium:
    name: "Специалист Ольга"
    emoji: "😐"
    description: "Опытный пользователь, знает что хочет"
    difficulty: "medium"
  hard:
    name: "Директор Игорь"
    emoji: "😤"
    description: "Требовательный руководитель, нужны точные ответы"
    difficulty: "hard"

# Промпты для генерации вопросов от симулированных пользователей
question_generation:
  base_prompt: |
    Ты — {character_name}, {character_description}.

    Сгенерируй ОДИН короткий вопрос (1-2 предложения) по теме "{topic}" для IT-поддержки.
    Вопрос должен быть в стиле персонажа:
    - Новичок: простые базовые вопросы, может не знать терминов
    - Специалист: конкретные технические вопросы
    - Директор: требовательный тон, нужна срочность и четкость

    Верни ТОЛЬКО текст вопроса, без объяснений.
  
  # Промпт для извлечения проблемы из чанка и создания вопроса
  extraction_prompt: |
    Ты — {character_name}, {character_description}.

    Прочитай следующий фрагмент документации:

    ---
    {chunk_content}
    ---

    На основе этого фрагмента:
    1. Определи одну конкретную проблему или ситуацию, которая там описана
    2. Сформулируй вопрос от лица пользователя {character_name}

    Стиль персонажа:
    - Новичок Вася: простые слова, неуверенность, не знает терминов
    - Специалист Ольга: точно и профессионально, знает что хочет
    - Директор Игорь: требовательный тон, срочность, может быть недоволен

    Верни ТОЛЬКО сформулированный вопрос (1-3 предложения), как будто ты реальный пользователь.
    НЕ пиши 'вопрос:', 'проблема:' и т.п. - только сам вопрос.
  
  # Промпт для перефразирования готового вопроса в стиле персонажа
  rephrase_prompt: |
    Ты — {character_name}, {character_description}.

    Перефразируй следующий вопрос в своем стиле:

    {question}

    ВАЖНО:
    - Новичок Вася: используй простые слова, может не знать терминов, говори неуверенно
    - Специалист Ольга: говори точно и профессионально, знаешь что хочешь
    - Директор Игорь: требовательный тон, добавь срочность, можешь быть недовольным

    Верни ТОЛЬКО перефразированный вопрос (1-2 предложения), без объяснений.

# Промпты для оценки ответов операторов
evaluation:
  evaluation_prompt: |
    Ты — строгий эксперт по оценке работы операторов IT-поддержки.

    ВОПРОС ПОЛЬЗОВАТЕЛЯ:
    {question}

    КОНТЕКСТ ИЗ БАЗЫ ЗНАНИЙ:
    {context}

    ОТВЕТ ОПЕРАТОРА:
    {user_answer}

    ЭТАЛОННЫЙ ОТВЕТ:
    {ai_answer}

    Оцени ответ оператора по шкале 0-100 и дай краткую обратную связь (2-3 предложения).

    ВАЖНЫЕ ПРАВИЛА ОЦЕНКИ:
    - Короткие ответы (меньше 20 слов) - максимум 30 баллов
    - Односложные ответы ("ок", "хорошо", "да") - 0-10 баллов
    - Ответ без конкретного решения проблемы - максимум 40 баллов
    - Грубые или непрофессиональные ответы - 0 баллов
    - Отличный ответ (80-100 баллов) должен быть ПОЛНЫМ, ВЕЖЛИВЫМ, СТРУКТУРИРОВАННЫМ и содержать КОНКРЕТНОЕ РЕШЕНИЕ

    Критерии оценки:
    1. Правильность решения (40 баллов) - дан ли корректный ответ на вопрос
    2. Полнота (20 баллов) - достаточно ли деталей для решения
    3. Тон и вежливость (20 баллов) - профессионализм общения
    4. Структурированность (20 баллов) - понятность изложения

    Верни ответ в формате:
    SCORE: [число 0-100]
    FEEDBACK: [текст обратной связи]

    Будь объективен и строг. Высокие баллы даются только за ДЕЙСТВИТЕЛЬНО хорошие ответы.

  validation_prompt: |
    Проанализируй отзыв и определи, соответствует ли оценка {initial_score} баллов содержанию отзыва.

    ОТЗЫВ:
    {feedback}

    ОТВЕТ ОПЕРАТОРА:
    {user_answer}

    Верни ТОЛЬКО число от 0 до 100 - справедливую оценку на основе отзыва.
    Если отзыв содержит критику, недостатки, ошибки - снижай оценку.
    Если отзыв положительный и хвалит ответ - оставь высокую оценку.

    Правила:
    - "не решает проблему", "неполный", "недостаточно" = максимум 40 баллов
    - "есть недочеты", "можно улучшить" = 50-70 баллов
    - "хороший ответ", "верно", "правильно" = 70-90 баллов
    - "отличный", "профессионально", "все учтено" = 90-100 баллов

    Верни ТОЛЬКО одно число (0-100):

# Промпты для генерации подсказок
hints:
  hint_prompt: |
    Дай краткую подсказку (1-2 предложения) оператору, как лучше ответить на этот вопрос:

    ВОПРОС: {question}

    КОНТЕКСТ: {context}

    Подсказка должна направить оператора, но не давать готовый ответ.

# Промпты для генерации эталонных ответов
ai_answers:
  ai_answer_prompt: |
    Ты — опытный оператор IT-поддержки. Дай КРАТКИЙ профессиональный ответ (2-3 предложения) на вопрос пользователя.

    ВОПРОС: {question}

    КОНТЕКСТ ИЗ БЗ: {context}

    Ответ должен быть вежливым, структурированным и содержать конкретное решение.